name: 'Slack release message BeOp'
description: 'A GitHub Action to push a slack webhook'
branding:
  icon: 'message-circle'
  color: 'gray-dark'
inputs:
  version:
    description: "The version you're releasing (e.g. v1.0.1, 1.0.1)"
    required: true
  changelog:
    description: 'The contents of your changelog file, each version needs to start with `## x.y.z`'
    required: false
  slack_webhook_url:
    description: 'Your slack webhook URL'
    required: true
runs:
  using: "node16"
  main: "dist/index.js"
