name: 'Slack release message'
description: 'Greet someone and record the time'
inputs:
  version:
    description: 'The version you're releasing (e.g. v1.0.1, 1.0.1)'
    required: true
  changelog:
    description: 'The contents of your changelog file, each version needs to start with `## x.y.z`'
    required: false
runs:
  using: 'node14'
  main: 'index.js'